services:

  php-apache:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: app
      MARIADB_USER: appuser
      MARIADB_PASSWORD: password
    ports:
      - "9906:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_conf:/etc/mysql

volumes:
  mariadb_data:
  mariadb_conf: