services:

  keycloak:
    image: keycloak/keycloak:22.0
    hostname: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
    command: ["start-dev", "--import-realm", "--health-enabled=true"]
    healthcheck:
        test: "bash /opt/keycloak/health-check.sh"
        interval: 5s
        timeout: 10s
        retries: 5
    volumes:
      - ./import:/opt/keycloak/data/import
      - ./extensions:/opt/keycloak/providers
      - ./health-check.sh:/opt/keycloak/health-check.sh
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data: