USE [master]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled')) PRINT 'FULLTEXT INSTALLED' ELSE PRINT 'FULLTEXT NOT INSTALLED'
GO

IF (4 = (SELECT dss.[status] FROM sys.dm_server_services dss WHERE dss.[servicename] LIKE N'SQL Server Agent (%'))  PRINT 'SQL SERVER AGENT RUNNING' ELSE PRINT 'SQL SERVER AGENT NOT RUNNING'
GO
