services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    volumes:
      # - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      # - ./data/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro