services:

sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=P@ssword
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
     - sqlserver_data:/var/opt/mssql/data

volumes:
  sqlserver_data: