{
 "title": "Sample dotnet-monitor dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{job=\"monitor\"}",
     "legendFormat": "Gen 0 Size"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{job=\"monitor\"}",
     "legendFormat": "Gen 1 Size"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{job=\"monitor\"}",
     "legendFormat": "Gen 2 Size"
    },
    {
     "expr": "systemruntime_loh_size_bytes{job=\"monitor\"}",
     "legendFormat": "LOH Size"
    },
    {
     "expr": "systemruntime_poh_size_bytes{job=\"monitor\"}",
     "legendFormat": "POH Size"
    }
   ]
  },
  {
   "title": "Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gc_heap_size_bytes{job=\"monitor\"}",
     "legendFormat": "GC Heap Size"
    },
    {
     "expr": "systemruntime_working_set_bytes{job=\"monitor\"}",
     "legendFormat": "Working Set"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_cpu_usage_ratio{job=\"monitor\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{job=\"monitor\"}",
     "legendFormat": "Alloc rate"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{job=\"monitor\"}",
     "legendFormat": "Total Fragmentation"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio{job=\"monitor\"}",
     "legendFormat": "% Time in GC"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } }
 ]
}