x-common-variables: &common
  MSSQL_SA_PASSWORD: P@ssw0rd

services:
  
  sqlserver:
    build:
      dockerfile: mssql-server2022-fts.Dockerfile
      tags:
        - mssql-server2022:fts
    ports:
      - "1433:1433"
    environment:
      <<: *common
      ACCEPT_EULA: Y
      MSSQL_AGENT_ENABLED: true
      MSSQL_PID: Developer
      # USE_OTELCOL: true
    volumes:
      - ./backups:/var/backups
      - ./mssql-server.otelcol-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - sqlserver_data:/var/opt/mssql

  mssql-tools18:
    build:
      dockerfile: mssql-tools18-alpine.Dockerfile
      tags:
        - mssql-tools18:alpine-3.20
    profiles:
      - init
    depends_on:
      - sqlserver
    environment:
      <<: *common
      MSSQL_HOST: sqlserver
      # MSSQL_HOST_CONNECTION_MAX_RETRIES: 5
      # MSSQL_HOST_CONNECTION_RETRY_WAIT_SECONDS: 3
    volumes:
      - ./scripts:/var/scripts:ro
    command: /var/scripts/run-scripts.sh

volumes:
  sqlserver_data: