x-common-variables: &common
  MSSQL_SA_PASSWORD: P@ssw0rd

services:
  
  sqlserver-ef:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      <<: *common
      MSSQL_PID: Developer
      ACCEPT_EULA: Y
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
     - sqlserver_data:/var/opt/mssql

  init-sqlserver-ef:
    image: mcr.microsoft.com/mssql-tools:latest
    profiles:
      - init
    depends_on:
      sqlserver-ef:
        condition: service_healthy
    environment:
      <<: *common
      MSSQL_HOST: sqlserver-ef
    volumes:
      - ./init:/init
    command: /init/run-initialization.sh

volumes:
  sqlserver_data: