services:
  minio:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /export/gitlab && /usr/bin/minio server /export'
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data: