services:

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
      - POSTGRES_ADDITIONAL_DATABASES= # leave empty if no additional databases are needed
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=en_US
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:24
    depends_on:
      - postgres
    ports:
      - "8978"
    environment:
      - CLOUDBEAVER_APP_GRANT_CONNECTIONS_ACCESS_TO_ANONYMOUS_TEAM=true
      - CB_SERVER_NAME=Test Server
      - CB_ADMIN_NAME=cbadmin
      - CB_ADMIN_PASSWORD=P@ssw0rd
    volumes:
      - ./cloudbeaver/data-sources.json:/opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
      - ./cloudbeaver/product.conf:/opt/cloudbeaver/workspace/.data/.product.runtime.conf
      - cloudbeaver_logs:/opt/cloudbeaver/logs
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  postgres_data:
  cloudbeaver_logs:
  cloudbeaver_data: