services:

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=master
    volumes:
      # - ./data:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: