services:

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
      - POSTGRES_ADDITIONAL_DATABASES= # leave empty if no additional databases are needed
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=en_US
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    depends_on:
      - postgres
    ports:
      - "80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./pgadmin/pgpass:/pgpass
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    user: root
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"

volumes:
  postgres_data:
  pgadmin_data: